### ISSUE TITLE
FAQ section does not exist or it is unreachable

### ISSUE THREAD

**Issue by IkerAlus** [polkadart/docs#1]
From https://polkadart.dev/guides/overview/ , click on FAQ section, it directs to https://polkadart.dev/guides/listen-blocks/

Also, https://polkadart.dev/guides/faq/ seems to be empty

**Comment by leonardocustodio** [comment]
I actually removed the FAQ and replaced by the guides as we still don't have many asked questions 😅

It seems I forgot to remove the button, I will do that now.

Thank you for the report 😄
